"""init tables

Revision ID: 36d21545a5b4
Revises: 
Create Date: 2025-12-29 17:17:38.515461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d21545a5b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('detail_url', sa.String(length=512), nullable=True),
    sa.Column('community_name', sa.String(length=255), nullable=True),
    sa.Column('community_url', sa.String(length=512), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('layout', sa.String(length=32), nullable=True),
    sa.Column('orientation', sa.String(length=32), nullable=True),
    sa.Column('decoration', sa.String(length=32), nullable=True),
    sa.Column('floor', sa.String(length=64), nullable=True),
    sa.Column('building_type', sa.String(length=32), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('build_year', sa.Integer(), nullable=True),
    sa.Column('total_price_wan', sa.Float(), nullable=True),
    sa.Column('total_price_yuan', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=True),
    sa.Column('follow_count', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('cover_image', sa.String(length=512), nullable=True),
    sa.Column('crawl_time', sa.DateTime(), nullable=True),
    sa.Column('is_annotated', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_houses_house_id'), 'crawl_houses', ['house_id'], unique=True)
    op.create_index(op.f('ix_crawl_houses_id'), 'crawl_houses', ['id'], unique=False)
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_house_id', sa.String(length=64), nullable=True),
    sa.Column('area_sqm', sa.Float(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('age_years', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_houses_id'), 'houses', ['id'], unique=False)
    op.create_index(op.f('ix_houses_source_house_id'), 'houses', ['source_house_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_houses_source_house_id'), table_name='houses')
    op.drop_index(op.f('ix_houses_id'), table_name='houses')
    op.drop_table('houses')
    op.drop_index(op.f('ix_crawl_houses_id'), table_name='crawl_houses')
    op.drop_index(op.f('ix_crawl_houses_house_id'), table_name='crawl_houses')
    op.drop_table('crawl_houses')
    # ### end Alembic commands ###
